### ISSUE TITLE
master pod failure

### ISSUE THREAD

**Issue by ennesuysal** [reactive-tech/kubegres#32] opened 2021-08-11 15:10 UTC
When the master pod(1) is crashed, the second pod starts again as the master and a new pod(4) is created because the first pod is crashed. While the second pod and the fourth pod work synchronously, the third pod works alone.

**Comment by alex-arica** [comment] 2021-08-12 09:26
Thank you for your message. 

I tried to reproduce your observations.
The 1st time I deployed my Postgres cluster, my pods were as follows:

```
kubectl get pods 
NAME             READY   STATUS    RESTARTS   AGE
mypostgres-1-0   1/1     Running   0          74s
mypostgres-2-0   1/1     Running   0          55s
mypostgres-3-0   1/1     Running   0          31s
```

Once "mypostgres-1-0" crashed, Kubegres promoted "mypostgres-2-0" as Primary. The pods were as follows:
```
kubectl get pods
NAME             READY   STATUS    RESTARTS   AGE
mypostgres-2-0   1/1     Running   0          92s
mypostgres-3-0   1/1     Running   0          15m
mypostgres-4-0   1/1     Running   0          61s
```

I checked the logs of "mypostgres-3-0" (which you described as the third pod) and its contents are as follows:
```
2021-08-12 09:04:12.356 GMT [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-12 09:04:12.356 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-12 09:04:12.356 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-12 09:04:12.368 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-12 09:04:12.378 GMT [26] LOG:  database system was interrupted; last known up at 2021-08-12 09:04:11 GMT
2021-08-12 09:04:12.723 GMT [26] LOG:  entering standby mode
2021-08-12 09:04:12.733 GMT [26] LOG:  redo starts at 0/4000028
2021-08-12 09:04:12.738 GMT [26] LOG:  consistent recovery state reached at 0/4000100
2021-08-12 09:04:12.738 GMT [1] LOG:  database system is ready to accept read only connections
2021-08-12 09:04:12.746 GMT [30] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
2021-08-12 09:17:38.556 GMT [30] LOG:  replication terminated by primary server
2021-08-12 09:17:38.556 GMT [30] DETAIL:  End of WAL reached on timeline 1 at 0/50001C0.
2021-08-12 09:17:38.556 GMT [30] FATAL:  could not send end-of-streaming message to primary: no COPY in progress
2021-08-12 09:17:38.556 GMT [26] LOG:  invalid record length at 0/50001C0: wanted 24, got 0
2021-08-12 09:17:38.652 GMT [1685] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:17:43.564 GMT [1700] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:17:48.568 GMT [1708] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:17:53.573 GMT [1723] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:17:58.578 GMT [1731] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:18:03.580 GMT [1746] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:18:08.585 GMT [1754] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:18:13.715 GMT [1769] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-12 09:18:18.595 GMT [1777] LOG:  fetching timeline history file for timeline 2 from primary server
2021-08-12 09:18:18.607 GMT [1777] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
2021-08-12 09:18:18.607 GMT [1777] LOG:  replication terminated by primary server
2021-08-12 09:18:18.607 GMT [1777] DETAIL:  End of WAL reached on timeline 1 at 0/50001C0.
2021-08-12 09:18:18.607 GMT [26] LOG:  new target timeline is 2
2021-08-12 09:18:18.608 GMT [1777] LOG:  restarted WAL streaming at 0/5000000 on timeline 2
```

In the logs above, we can observe that:
- at "09:17:38" Primary crashed and the streaming was terminated. 
- after 40 seconds at "09:18:18", the streaming resumed with the new Primary

Perhaps on your machine it took longer than 40 seconds for the third pod to resume streaming? And you thought it was working alone?

If you could reproduce the issue and share the logs of the third pod, it would help me to understand.

**Comment by ennesuysal** [comment] 2021-08-12 10:50
Thanks for reply. Logs of pod3 in my cluster is like below.
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-08-12 10:43:15.990 GMT [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-12 10:43:15.990 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-12 10:43:15.990 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-12 10:43:15.992 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-12 10:43:15.996 GMT [27] LOG:  database system was interrupted; last known up at 2021-08-12 10:43:14 GMT
2021-08-12 10:43:16.053 GMT [27] LOG:  entering standby mode
2021-08-12 10:43:16.056 GMT [27] LOG:  redo starts at 0/4000028
2021-08-12 10:43:16.057 GMT [27] LOG:  consistent recovery state reached at 0/4000100
2021-08-12 10:43:16.057 GMT [1] LOG:  database system is ready to accept read only connections
2021-08-12 10:43:16.067 GMT [31] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
2021-08-12 10:44:58.588 GMT [31] LOG:  replication terminated by primary server
2021-08-12 10:44:58.588 GMT [31] DETAIL:  End of WAL reached on timeline 1 at 0/5000990.
2021-08-12 10:44:58.588 GMT [31] FATAL:  could not send end-of-streaming message to primary: no COPY in progress
2021-08-12 10:44:58.589 GMT [27] LOG:  invalid record length at 0/5000990: wanted 24, got 0
2021-08-12 10:44:58.597 GMT [223] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:03.644 GMT [238] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:08.602 GMT [246] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:13.610 GMT [263] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:18.609 GMT [271] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:23.613 GMT [288] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:28.618 GMT [296] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:33.622 GMT [311] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:38.625 GMT [319] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:43.630 GMT [335] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:48.633 GMT [344] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:53.639 GMT [359] FATAL:  could not connect to the primary server: could not translate host name "yartu-postgres" to address: Temporary failure in name resolution
2021-08-12 10:45:58.643 GMT [367] FATAL:  database system identifier differs between the primary and standby
2021-08-12 10:45:58.643 GMT [367] DETAIL:  The primary's identifier is 6995452135159111719, the standby's identifier is 6995465267056402471.
2021-08-12 10:46:03.647 GMT [383] FATAL:  database system identifier differs between the primary and standby
2021-08-12 10:46:03.647 GMT [383] DETAIL:  The primary's identifier is 6995452135159111719, the standby's identifier is 6995465267056402471.
2021-08-12 10:46:08.651 GMT [391] FATAL:  database system identifier differs between the primary and standby
2021-08-12 10:46:08.651 GMT [391] DETAIL:  The primary's identifier is 6995452135159111719, the standby's identifier is 6995465267056402471.
2021-08-12 10:46:13.655 GMT [406] FATAL:  database system identifier differs between the primary and standby
2021-08-12 10:46:13.655 GMT [406] DETAIL:  The primary's identifier is 6995452135159111719, the standby's identifier is 6995465267056402471.
2021-08-12 10:46:18.659 GMT [414] FATAL:  database system identifier differs between the primary and standby
2021-08-12 10:46:18.659 GMT [414] DETAIL:  The primary's identifier is 6995452135159111719, the standby's identifier is 6995465267056402471.
2021-08-12 10:46:23.664 GMT [430] FATAL:  database system identifier differs between the primary and standby
2021-08-12 10:46:23.664 GMT [430] DETAIL:  The primary's identifier is 6995452135159111719, the standby's identifier is 6995465267056402471.
```

**Comment by alex-arica** [comment] 2021-08-12 11:06
Thank you for the logs, very useful. This message is interesting "database system identifier differs between the primary and standby". It means that the new Primary DB is not recognised as the original DB by the Replica. 
I am not able to reproduce it. 

How did you crash pod1 ?

**Comment by ennesuysal** [comment] 2021-08-12 11:28
I ran the commands at below:
`kubectl delete pod mypostgres-3-0`
`kubectl delete pod mypostgres-3-0 --force`

Both gave the same log

**Comment by alex-arica** [comment] 2021-08-12 11:54
Yes it could be Minicube. When I have sometime, I will download Minicube and see if I can reproduce it.
For my local developments, I am using [Kind](https://kind.sigs.k8s.io/).

**Comment by ennesuysal** [comment] 2021-08-12 12:05
Thanks a lot for your help, I'm following. Your project is really a great.

**Comment by alex-arica** [comment] 2021-08-12 12:44
Thank you for your support. Much appreciated!

**Comment by ennesuysal** [comment] 2021-08-13 09:10
I ran the project in the kind cluster, this time it worked, but when I restarted the cluster, pod1 could not see the written data after it was closed and pod 3 gave this error:

`PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-08-13 08:56:15.944 GMT [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-13 08:56:15.944 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-13 08:56:15.944 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-13 08:56:15.946 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-13 08:56:15.950 GMT [26] LOG:  database system was shut down in recovery at 2021-08-13 08:55:40 GMT
2021-08-13 08:56:15.950 GMT [26] LOG:  entering standby mode
2021-08-13 08:56:15.953 GMT [26] LOG:  consistent recovery state reached at 0/7000A78
2021-08-13 08:56:15.953 GMT [26] LOG:  invalid record length at 0/7000A78: wanted 24, got 0
2021-08-13 08:56:15.954 GMT [1] LOG:  database system is ready to accept read only connections
2021-08-13 08:56:15.963 GMT [30] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:15.972 GMT [31] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:20.973 GMT [32] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:25.977 GMT [40] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:30.981 GMT [49] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:35.985 GMT [58] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:40.989 GMT [67] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:45.993 GMT [75] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:50.997 GMT [83] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:56:56.001 GMT [92] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:57:01.005 GMT [101] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2
2021-08-13 08:57:06.009 GMT [109] FATAL:  highest timeline 1 of the primary is behind recovery timeline 2`

**Comment by alex-arica** [comment] 2021-08-13 09:37
Thank you for your message. It is great that you are using Kind. I like its multi nodes features.

How did you restart the Kind cluster?

**Comment by ennesuysal** [comment] 2021-08-13 09:49
Actually I deleted Kubegres object with the command at below and recreate it.
`kubectl delete -f postgres/postgres.yaml`

**Comment by alex-arica** [comment] 2021-08-13 09:52
Ok I see. 
By default, in Kind the storage class does not delete the PV and PVC when a Kubegres object is deleted. After deleting the cluster, you need to delete the associated PV and PVC manually. And then you can create a new cluster of same name. Otherwise, it seems to reuse the same PV and PVC but with the wrongly expected data.

**Comment by alex-arica** [comment] 2021-08-13 10:10
I tried to delete a kubegres cluster and create it again. The PV and PVC were not deleted so the newly created cluster reused them. 

At the end it worked, but it took about 3 mins for the replica instances to start streaming again.

The logs as follows:

Pod 1 Primary (that took few minutes):
```
kubectl logs mypostgres-1-0

PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-08-13 10:02:47.686 GMT [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-13 10:02:47.686 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-13 10:02:47.686 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-13 10:02:47.696 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-13 10:02:47.706 GMT [26] LOG:  database system was shut down at 2021-08-13 10:02:44 GMT
2021-08-13 10:02:47.713 GMT [1] LOG:  database system is ready to accept connections
```

Pod 2 Replica (it took about 3 mins to stream again):
```
kubectl logs mypostgres-2-0

PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-08-13 10:02:35.849 GMT [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-13 10:02:35.849 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-13 10:02:35.849 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-13 10:02:35.859 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-13 10:02:35.870 GMT [26] LOG:  database system was shut down in recovery at 2021-08-13 10:02:22 GMT
2021-08-13 10:02:35.870 GMT [26] LOG:  entering standby mode
2021-08-13 10:02:35.876 GMT [26] LOG:  redo starts at 0/50000D8
2021-08-13 10:02:35.876 GMT [26] LOG:  consistent recovery state reached at 0/5000110
2021-08-13 10:02:35.876 GMT [26] LOG:  invalid record length at 0/5000110: wanted 24, got 0
2021-08-13 10:02:35.876 GMT [1] LOG:  database system is ready to accept read only connections
2021-08-13 10:02:35.884 GMT [30] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
2021-08-13 10:02:44.939 GMT [30] LOG:  replication terminated by primary server
2021-08-13 10:02:44.939 GMT [30] DETAIL:  End of WAL reached on timeline 1 at 0/5000188.
2021-08-13 10:02:44.940 GMT [30] FATAL:  could not send end-of-streaming message to primary: no COPY in progress
2021-08-13 10:02:44.940 GMT [26] LOG:  invalid record length at 0/5000188: wanted 24, got 0
2021-08-13 10:02:45.003 GMT [38] FATAL:  could not connect to the primary server: could not translate host name "mypostgres" to address: Name or service not known
2021-08-13 10:04:59.437 GMT [46] FATAL:  could not connect to the primary server: could not connect to server: Connection timed out
		Is the server running on host "mypostgres" (10.244.2.4) and accepting
		TCP/IP connections on port 5432?
2021-08-13 10:04:59.441 GMT [290] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
```

Pod 3 Replica (it took about 3 mins to stream again):
```
kubectl logs mypostgres-3-0

PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-08-13 10:02:13.826 GMT [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-13 10:02:13.826 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-13 10:02:13.826 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-13 10:02:13.836 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-13 10:02:13.847 GMT [26] LOG:  database system was shut down in recovery at 2021-08-13 10:02:10 GMT
2021-08-13 10:02:13.847 GMT [26] LOG:  entering standby mode
2021-08-13 10:02:13.853 GMT [26] LOG:  redo starts at 0/50000D8
2021-08-13 10:02:13.853 GMT [26] LOG:  consistent recovery state reached at 0/5000110
2021-08-13 10:02:13.853 GMT [26] LOG:  invalid record length at 0/5000110: wanted 24, got 0
2021-08-13 10:02:13.854 GMT [1] LOG:  database system is ready to accept read only connections
2021-08-13 10:02:13.862 GMT [30] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
2021-08-13 10:02:44.940 GMT [30] LOG:  replication terminated by primary server
2021-08-13 10:02:44.940 GMT [30] DETAIL:  End of WAL reached on timeline 1 at 0/5000188.
2021-08-13 10:02:44.940 GMT [30] FATAL:  could not send end-of-streaming message to primary: no COPY in progress
2021-08-13 10:02:44.940 GMT [26] LOG:  invalid record length at 0/5000188: wanted 24, got 0
2021-08-13 10:02:44.942 GMT [66] FATAL:  could not connect to the primary server: could not connect to server: Connection refused
		Is the server running on host "mypostgres" (10.244.2.4) and accepting
		TCP/IP connections on port 5432?
2021-08-13 10:04:59.437 GMT [74] FATAL:  could not connect to the primary server: could not connect to server: Connection timed out
		Is the server running on host "mypostgres" (10.244.2.4) and accepting
		TCP/IP connections on port 5432?
2021-08-13 10:04:59.442 GMT [332] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
```

**Comment by ennesuysal** [comment] 2021-08-13 10:21
Did you delete pod1 before delete cluster?

**Comment by alex-arica** [comment] 2021-08-13 10:23
I did not delete Pod 1. 
Oh you mean you deleted Pod 1, waited for the failover to happen and then you deleted the cluster and recreated it?

**Comment by ennesuysal** [comment] 2021-08-13 10:24
Yes, I meant it. I'm sorry my english is not good.

**Comment by alex-arica** [comment] 2021-08-13 10:37
No worries.

I confirm that for this to work with the storage classes used by kind, you need to delete the PVC and PV manually then after create your cluster.

Moreover, when you delete a Kubegres resource, Kubernetes deletes the state of that Kubegres object. It means if you create a new Kubegres cluster with same name, a brand new cluster will be created with pod1, pod2 and pod3.

**Comment by ennesuysal** [comment] 2021-08-13 10:46
Okay I got it but it could be nicer if the old state was saved, maybe you will add this option in further versions. Thanks a lot for this project and your helpings.

**Comment by alex-arica** [comment] 2021-08-13 10:50
I cannot save the old state on the operator level because this is a feature of Kubernetes.

When you run that command:
```
kubectl delete -f postgres/postgres.yaml
```

then the state of the resource that you deleted is remove from ETCD (Kubernetes database). If you remove a Kubegres cluster, then Kubernetes removes all its states from ETCD.

**Comment by ennesuysal** [comment] 2021-08-13 10:54
I understood. I thought it could be done with persistent volumes. So why doesn't the new pod get the name of the crashed pod but get a new number?

**Comment by alex-arica** [comment] 2021-08-13 10:57
Persistent volume has the state of the PosgreSql database.
However, when you delete a Kubegres object, you are also delete the states about that particular cluster from ETCD. And without that state the operator does not know the history and try to create a new cluster.

**Comment by alex-arica** [comment] 2021-08-17 08:49
After further check, the issue with Minicube is not related to Kubegres. Closing this issue as a result.

**Closed by alex-arica** 2021-08-17 08:49 UTC
