### ISSUE TITLE
Delete pvc when pod is deleted

### ISSUE THREAD

**Issue by owenchenxy** [reactive-tech/kubegres#71] opened 2021-12-01 02:44 UTC
hi Alex,

currently, while a failover happend, a new pvc will be created along will the new replica pod. However, the old pvc remained even though the old replica pod is deleted. If there are frequent failover happens somehow, there will be lots of pvcs, which could run out the storage. 

Could you make some improvement, so that the pvc will be deleted along with the deleted pod?

**Comment by leonz** [comment] 2021-12-01 18:27
We just noticed this as well and it is causing major problems for us.

**Comment by alex-arica** [comment] 2021-12-06 16:25
Thank you both for your feedback. There is a ticket about the issue that you reported: #20
I am going to prioritise it but I cannot commit to any dates.

**Comment by alex-arica** [comment] 2021-12-06 16:27
I am closing this issue as it is a duplicate of #20

**Closed by alex-arica** 2021-12-06 16:27 UTC
